### ISSUE TITLE
Server message: unit info

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#1]
Appena confermata la connessione (e immagino anche quando ci saranno variazioni, tipo sui punti vita), il server invia le info dell'unità:

``` javascript
{
        mt: 3,
        pid: player id,
        uid: unit id,
        n: 'nickname unit',
        x: coordinate x,
        y: coordinate y,
        h: hit points,
        r: id razza,
        g: id gender,
        v: id variante,
        s: velocità camminando, pixel/s,
        i: velocità di corsa, pixel/s,
        b: visibilità in pixels
}
```

**Comment by NikolasMosca** [comment]
Sure, ci saranno da aggiungere dei parametri nel caso che debbano essere visibile altre informazioni tipo l'energia o altro.. ma se si può vedere solo la vita allora non bisogna aggiungere nulla.

Per il nome dell'icona è in caso di un oggetto immagino.

mt cosa significa?

Se mt non è un tipo forse conviene aggiungere un campo tipo cosi da poter differenziare i personaggi dai mostri o dagli oggetti o dai muri :-)

**Comment by sincontri** [comment]
mt identifica il tipo di messaggio, in questo caso le info dell'unità, in teoria ce ne sarà uno per ogni tipo di messaggio così ti fai uno switch/case o if per vedere cosa/dove mettere le info che ricevi; tienile come oggetto json in memoria così è più efficiente.

Il ts (timestamp) lo toglierei, risparmiamo spazio, che dici?

Oltre agli hit points ci saranno tutte le altre caratteristiche, per adesso usiamo solo quella.

Le icone dei personaggi stanno nella cartella: icons/players/base e poi aggiungi il nome e carichi l'immagine giusto?

**Comment by NikolasMosca** [comment]
Ok perfetto.. quindi campo tipo è mt.. per il timestamp si lo toglierei.. semplicemente per il ping a me basta vedere quanto ci mette ad arrivare.. per il resto perfect :-)

**Comment by sincontri** [comment]
Per il campo mt mi sono fatto una struttura fissa, altrimenti il codice diventa illeggibile:

``` javascript
var ServerMessageTypes = {
  CONFIRM_CONNECTION: 1,
  CLOSE: 2,
  UNIT_INFO: 3
};
```

**Comment by sincontri** [comment]
Ci sarà poi da passare l'icona con un id, ma lo facciamo più avanti, per adesso va bene il nome del file.

**Comment by NikolasMosca** [comment]
beh a questo punto iniziamo subito con gli id.. altrimenti dopo ci troviamo male xD tanto anche per quello a me e a te basta un oggetto per associare nome_file con id

**Comment by sincontri** [comment]
Ok allora ti mando 3 id per identificare l'icona: razza, sesso e variante (colore o altro), vedi la issue #2 .
Modifico la definizione del messaggio in cima alla issue.

**Comment by sincontri** [comment]
Ho aggiunto i campi _pid_ (id del player) e _uid_ (id della unità), sicuramente ti serviranno prima o poi.

**Comment by NikolasMosca** [comment]
Ok sono stati aggiunti.. forse ti è sfuggito il pid, non lo vedo nel messaggio :-)

**Comment by sincontri** [comment]
Aggiunti i campi:

**mh**: max hp (intero),
**e**: energy (intero),
**me**: max energy (intero)

**Comment by sincontri** [comment]
Aggiunti campi max_speed e max_speed_run ma a te non dovrebbero servire :+1:
