### ISSUE TITLE
Objects definition

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#10]
Per adesso definiamo il **type** nell'anagrafica objects così:

``` javascript
{
  ARMOUR: 1
}
```

**Comment by NikolasMosca** [comment]
Ok perfetto :-) inserito tra i miei oggetti.. procedo nel frattempo con le altre modifiche ;-)

**Comment by sincontri** [comment]
Ci siamo, aggiunti gloves e cloak, poi verrà il resto :+1:
