### ISSUE TITLE
Server message: unit collision

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#12]
In caso di collisione, il server sposta l'unità alla posizione precedente e la invia al client (comprese le unità in raggio visibile come al solito):

``` javascript
{
  mt: 10,
  x: x,
  y: y
}
```

**Comment by NikolasMosca** [comment]
teoricamente è implementata.. vedremo poi con i test se è funzionante :-)

**Comment by sincontri** [comment]
Sembra a posto, chiudo.
