### ISSUE TITLE
Selezione Unità

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#13]
Siccome le informazioni sulle unità che appartengono a un giocatore sono riservate, stavo pensando di implementare una fase di selezione dell'unità subito dopo la connessione.

Altrimenti sarebbe necessario sviluppare un'altra interfaccia a parte che comunque richiede l'autenticazione, non credo valga la pena.

Questo implica un messaggio da parte del server con l'elenco completo delle unità del giocatore; dopodichè la connessione sul server rimane in sospeso finchè non riceve un messaggio apposito con l'id dell'unità scelta.

Che dici?

**Comment by sincontri** [comment]
Se ti piace, farei una paginetta nel client (o un popup) con un elenco delle unità per righe centrato nello schermo; ogni riga avrebbe all'inizio l'icona dell'unità e poi il nome; più avanti chiaramente metteremo anche livello o altre info.

**Comment by sincontri** [comment]
Ho lasciato tutto com'era per non rompere il client, ma ho già aggiunto il messaggio di selezione unità prima del unit_info:

``` javascript
{
  mt: 11,
  a: [
    {"id":1,"unitName":"Test","race_id":12,"gender_id":2,"variant_id":1,"hp":30,"energy":20,"mapName":"Starter land"},
    {"id":3,"unitName":"Ste2","race_id":1,"gender_id":2,"variant_id":2,"hp":50,"energy":40,"mapName":"Starter land"}
  ]
}
```

**Comment by sincontri** [comment]
Ti mando tutto, quindi puoi mostrare l'icona, hp energia e la mappa in cui si trova.

**Comment by NikolasMosca** [comment]
Che messaggio ti mando per dire che unita uso?

**Comment by sincontri** [comment]
Direi **mt: 3**, i primi due sono CLOSE e MOVE, dovrebbe bastare:

``` javascript
{
  mt: 3,
  i: id numerico unità scelta
}
```

**Comment by sincontri** [comment]
Ci siamo, chiudo.
