### ISSUE TITLE
oggetti vuoti nei messaggi

### ISSUE THREAD

**Issue by NikolasMosca** [sincontri/steniko#14]
Segnalo soltanto che capita sporadicamente che un oggetto sia vuoto (capita soltiamente il primo).

In casi specifici l'ho visto maggiormente sul messaggio con tipo mt:9

Mi arriva un messaggio con l'oggetto a null .. 

Ora ho inserito il controllo vedi tu se dare un occhio o meno ;)

**Comment by sincontri** [comment]
Per gli oggetti è corretto, perchè può esserci un terreno senza sopra nulla, o viceversa può esserci un oggetto senza sotto un terreno.

Invece mi pare di aver visto dei null anche nella anagrafica dei terreni, lì non dovrebbero esserci buchi, verificherò.

**Comment by sincontri** [comment]
Hai vito l'anagrafica completa dei terreni? Sono tutti 500 e passa, ho iniziato l'editor di mappe e servono anche a me ora ;)

**Comment by NikolasMosca** [comment]
yess .. non appena ho fatto un po l'interfaccia comincio a ottimizzare con la localStorage ;-)

**Comment by sincontri** [comment]
Mi sembra siamo a posto.
