### ISSUE TITLE
BUG oggetto json nell'object id

### ISSUE THREAD

**Issue by NikolasMosca** [sincontri/steniko#16]
Ciao ti segnalo che ho trovato un bug nel json.. 
quando cerco di fare la parse mi fallisce perchè è fatto in questo modo : 
" [ ' 82 ' ] "
Mentre invece me lo considera corretto cosi : 
' [ " 82 " ] '

Sta solo in una piccola svista con i quote :-)

**Comment by sincontri** [comment]
Hai ragione, ma non ci devono proprio essere gli apici :+1:

**Comment by sincontri** [comment]
Sistemato.
