### ISSUE TITLE
Errore su mapId 2

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#17]
Ho creato una seconda mappa id 2, ma ottengo errori entrando nel client:

CanvasEngine.js:279 Uncaught TypeError: Cannot read property 'id' of undefined

Poi nella selezione unità c'è null.

Ho messo il tuo omino sulla mappa 2 così magari domani mattina controlli ;)

**Comment by sincontri** [comment]
Mi ero dimenticato di mettere la riga in Maps :)
Mi sa che c'è ancora qualcosa che non va nel server con la mappa 2, dopo verifico.

**Comment by sincontri** [comment]
Ok era un errore del map editor, inseriva dei land_id non esistenti nell'anagrafica.

Ora rimane nel client, sembra non trovi la sotto cartella **grass**:

http://shadowadmin.altervista.org/client/icons/dc-dngn/grass/grass_flowers_yellow2.png Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by NikolasMosca** [comment]
Controllo se esiste il file e che il percorso sia giusto.. teoricamente dovrebbe prenderlo lol :smile:

**Comment by sincontri** [comment]
Era floor/grass, sistemato.
