### ISSUE TITLE
Get Item

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#18]
Il client manda il seguente messaggio al server per avvisare che un utente sta prendendo un oggetto:

``` javascript
{
  mt: 4,
  k: array oggetti,
  i: id della coordinata sulla mappa
}
```

Quando l'oggetto è stato effettivamente preso, il server risponde con lo stesso identico messaggio (però mt: **12**).
A tutte le altre unità sulla mappa viene mandata un messaggio con mt:**13** e _k_ e _i_ come sopra per avvisare che l'oggetti/gli oggetti sono stati presi.

**Comment by sincontri** [comment]
Occhio perché serve un messaggio diverso nel caso di oggetti multipli, per te sarà un mt **5** con solo l'id della mappa (l'utente non ha ancora scelto gli oggetti da raccogliere), perché devo implementare il lock tra l'arrivo del messaggio e il tuo successivo (mt **6**) per l'effettiva raccolta degli oggetti.

**Comment by NikolasMosca** [comment]
Ok ho implementato gli mt 12/13 .. non appena abbiamo fatto correttamente il drop degli oggetti singoli provvedo a strutturare il messaggio di lock come specificato nel secondo tuo commento :-)

**Comment by sincontri** [comment]
Mi sembra a posto, giusto?
