### ISSUE TITLE
Server message: map info

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#3]
Appena avvenuta la connessione, il server invia i dettagli della mappa su cui si trova l'unità del giocatore:

``` javascript
{
  mt: 4,
  i: { id: 1, name: 'Starter land', ground_icon: 'floor/dirt_e.png' },
  m: [ { id: 1, x: 230, y: 230, icon: 'wall/tree2_yellow.png' } ]
}
```

_i_ è un oggetto con i dati generali della mappa (nome, icona di default del terreno).
_m_ è un array di oggetti, ognuno rappresenta un oggetto sulla mappa con le sue coordinate.

Per il momento ti mando tutto, poi dovrei mandarti solo quello che puoi vedere.

**Comment by sincontri** [comment]
Mi son scordato che le icone per la mappa sono tutte nella cartella _dc-dngn_, poi per adesso specifico io la sottocartella; passo successivo sarà associare degli id alle icone e passare solo quelli.

**Comment by NikolasMosca** [comment]
Ok , solo una cosa : 
L'oggetto i e m, saranno sempre presenti nel messaggio di tipo (mt) 4?
O possono anche non esserci?
In questo modo so se fare il controllo o meno..

PS: Come detto prima, stiamo attenti a non fare troppo senza id.. altrimenti rischiamo di avere un rework pesante da fare

**Comment by sincontri** [comment]
Penso di si, preferisco creare un nuovo tipo di messaggio per le variazioni successive.

**Comment by NikolasMosca** [comment]
Immaginavo! Ok procedo con l'implementazione del messaggio.. cosi da vedere sto benedetto alberello sullo sfondo xD

**Comment by sincontri** [comment]
Dovrai anche disegnare la ground_icon usando la funzione del cerchio per disegnare solo nel raggio di visibilità dell'unità (che poi ti dovrò passare nel messaggio unit_info).
Stavo però pensando: visto che è solo di bellezza, se invece di usare un'icona da disegnare nella canvas, mettessimo uno sfondo ripetuto un po' più bellino, che dici?

Ad esempio:

``` javascript
// create pattern
    var ptrn = context.createPattern(img, 'repeat'); // Create a pattern with this image, and set it to "repeat".
    context.fillStyle = ptrn;
    context.fillRect(0, 0, canvas.width, canvas.height); // context.fillRect(x, y, width, height);
```

**Comment by NikolasMosca** [comment]
Si certo possiamo anche usare un pattern! La mia paura è solo che si vede che è statico.. ma è una cosa che affronteremo solo provando :-) Provo subito a metterla cosi da renderci piu conto.. e poi ci pensiamo ;-)

**Comment by sincontri** [comment]
Map info cambia usando gli id dei terreni e oggetti al posto che le info dirette, ad esempio:

``` javascript
{
  mt: 4,
  i: { id: 1, name: 'Starter land', ground_icon: 'floor/dirt_e' },
  m: [ { id: 1, x: 230, y: 230, land_id: 3, object_id: '[1,3]'} ]
}
```

Poi dovresti avere già in memoria le due anagrafiche terreni (lands) e oggetti (objects) in array per id e il gioco e fatto, dimmi se hai problemi.

**object_id** è una stringa che contiene un array di **id** oggetti in formato json.

**Comment by sincontri** [comment]
A posto! :+1:
