### ISSUE TITLE
Client message : Player movement

### ISSUE THREAD

**Issue by NikolasMosca** [sincontri/steniko#4]
Apro la issue per cominciare a imbastire un messaggio da mandare al server per far muovere il personaggio..

Penso si possa imbastire cosi :

``` javascript

 { d : x }
```

d : sta per direzione, x può essere dal classico 1/2/3/4 a up/down/sx/dx, scegliamo noi :-)

In questo modo il messaggio è corto e leggero e dice al server la propria intenzione.. ma cosi facendo è monodirezione, quindi movimenti obliqui non funzionerebbero.

Una seconda possibile sarebbe questa : 

``` javascript

{
   up : true,
   down : false,
   sx : true,
   dx : false
}
```

cosi facendo si puo camminare in obliquo ma entrambi dobbiamo fare un controllo di logica e consistenza.. ossia che se vai su, come in questo esempio, non puoi andare anche giu, stessa cosa con sinistra e destra.

Se hai qualche altra idea scrivi pure! ;-)

**Comment by sincontri** [comment]
Mi piace coi booleani, e poi ci vuole un messaggio dove mi mandi proprio le coordinate del click, poi ci pensa il server a farti arrivare lì, credo ;)

**Comment by sincontri** [comment]
Credo che dovrò farmi un timeout unico per il server per gestire i movimenti a intervalli, se rispondessi in tempo reale credo potrebbe scoppiare; anche lato client credo servirà sfoltire gli eventi, soprattutto dalla tastiera, altrimenti se uno tiene schiacciato una direzione potrebbe far partire parecchi messaggi la secondo.

**Comment by sincontri** [comment]
Occhio però, server un message type anche per i messaggi client.

**Comment by NikolasMosca** [comment]
Si anche io preferisco i bool, giusto bisogna anche prevedere un x e y facoltativo.. tenendo anche il conto del type come dici tu.. 

Quindi verrebbe fuori una cosa di questo tipo : 

``` javascript

{ mt:1 , x:100 , y:200 , up:false , down:false , left :false , right:true }

```

**Comment by NikolasMosca** [comment]
Secondo me dobbiamo trovare un modo per caricare il client.. altrimenti il server si ammazza di fatica.. 

Del tipo.. il movimento me lo gestisco io.. e all'intervallo x deciso fra noi, ti mando gli aggiornamenti della situazione.. e tu fai solo il check che siano possibili e che nn siano cheat.

Che ne pensi?

**Comment by NikolasMosca** [comment]
Secondo il sistema adottato riporto la soluzione presente :
Il client si muove liberamente e segnala ogni X ms (ora settato a 30) la posizione del personaggio.
A sua volta il server salva la posizione aggiornata e la segnala in broadcast a tutti i giocatori nel suo raggio la nuova posizione, che il client provvederà ad aggiornare, cosi da rendere visibile il movimento del personaggio.

Una cosa che rimarrà da fare come minor fix è fare un animazione di intermezzo da parte del client, cosi da ridurre il "mini scatto" nello spostamento
