### ISSUE TITLE
Mappa

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#5]
Ho sbagliato riguardo il raggio di visibilità, bisogna solo oscurare le parti non visibili (o schiarire leggermente quelle visibili, o entrambi), c'è una funzione apposta per la modifica del canale alpha che ho da qualche parte, devo solo trovarla.

Poi serve che il client si ricordi sempre gli oggetti già 'visti' in base a id giocatore e unitId.
Ci sarà poi la possibilità di spostare la visuale attraverso tutta la mappa e tornare a centrarla sul personaggio con un tasto/click.
Al limite poi se alcuni oggetti spariscono rispetto a quanto memorizzato, quando si torna in quella zona quelli spariscono effettivamente.

**Comment by NikolasMosca** [comment]
Ok per l'apha.. basta provare per vedere se è ok.
Per ricordarsi gli oggetti gia visti per ora ho lasciato appunto cosi.

Per spostare la visuale attraverso tutta la mappa cosa si intende? che puo vedere l'intera mappa senza sapere se ci sono mostri o oggetti?

Per far scomparire degli item mi verrà mandato un messaggio immagino

**Comment by sincontri** [comment]
Spostare la visuale significa che può vedere qualsiasi punto della mappa facendo scorrere lo schermo; chiaramente sarà visibile solo ciò che era stato già visto, e dovrà essere tutto 'oscurato' (con l'alpha se funziona, ora guardo) perchè fuori dalla visuale.

Sarebbe bello anche, più avanti, poter cliccare in qualsiasi punto della mappa e muovere l'unità verso il punto cliccato.

**Comment by NikolasMosca** [comment]
si ho capito.. per la minimappa quando creata cercherò di replicare la funzione di "pilota automatico" :-)

**Comment by sincontri** [comment]
Chiudo poi apriamo issue specifiche per ogni dettaglio.
