### ISSUE TITLE
Server message: unit login

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#6]
Nel caso stia entrando una nuova unità nel raggio di visibilità di quella del client, ti arriva un messaggio con **mt**: 5 (UNIT_LOGIN) e tutte le info esattamente come per il messaggio UNIT_INFO.

**Comment by NikolasMosca** [comment]
Per nuova unità intendi solo giocatori giusto? Non intendi oggetti o mostri vero?

**Comment by sincontri** [comment]
Si solo giocatori.

**Comment by sincontri** [comment]
Chiudo, dovremmo esserci, al limite riapriamo.
