### ISSUE TITLE
Server message: unit logoff

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#7]
Nel caso una unità esca vengono avvisate quelle che la possono vedere:

``` javascript
{
  mt: 7,
  id: id dell''unità che sta facendo logoff
}
```

**Comment by NikolasMosca** [comment]
È da prevedere anche un messaggio di log off da mandare con il client? O semplicemente fai un controllo su chi chiude la connessione?

**Comment by sincontri** [comment]
Per adesso ricevo l'evento di chiusura della websocket connection, quindi già è sufficiente così; se servirà un messaggio di chiusura dal client poi lo faremo.

**Comment by sincontri** [comment]
Ci siamo, chiudo.
