### ISSUE TITLE
Server message: lands

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#8]
Invia l'anagrafica dei terreni e oggetti del paesaggio, subito dopo la conferma connessione e prima delle unit_info:

``` javascript
{
  mt: 8,
  a: array di oggetti
}
```

Ogni oggetto è definito così:

``` javascript
{ 
  id: 1,
  icon: 'wall/tree2_yellow.png',
  obstacle: 1,
  width: 32,
  height: 32 
}
```

**Comment by sincontri** [comment]
Sarebbe bello, quando il client carica effettivamente le icone, segnalare al server le dimensioni reali diverse da quelle definite nell'anagrafica, che dici?
Ci pensiamo un attimo poi magari facciamo un messaggio client apposta.

**Comment by NikolasMosca** [comment]
Cosi ti rendo anche la vita piu semplice a te :-) sono d'accordo tanto io ce l'ho nell'array quel parametro.. mandarti un messaggino non mi costa nulla :P

Quindi questo va a sostituire il messaggio con mt = 5 -> MAP_INFO?

**Comment by sincontri** [comment]
No MAP_INFO c'è ancora ma non ha più direttamente le info dei terreni, ha due colonne nuove land_id e object_id che fanno riferimento agli id negli array delle due anagrafiche lands e objects, mandati in precedenza.

**Comment by sincontri** [comment]
In sostanza l'oggetto 'albero giallo' esiste solo una volta nell'array dell'anagrafica terreni (ad es. id 1); poi se nella mappa l'albero appare 100 volte ci sarà 1 in land_id per 100 righe con le proprie coordinate, non so se mi sono spiegato ;)

**Comment by NikolasMosca** [comment]
Sisi perfetto e implementato :)

**Comment by sincontri** [comment]
Pare che ci siamo, per adesso chiudo.
