### ISSUE TITLE
Server message: objects

### ISSUE THREAD

**Issue by sincontri** [sincontri/steniko#9]
Subito dopo l'anagrafica terreni:

``` javascript
{
  mt: 9,
  a: array di oggetti
}
```

Dove ogni oggetto al momento è definito:

``` javascript
{ 
    id: 1,
    name: 'Robe',
    real_name: 'Robe',
    icon: 'armour/robe1',
    type: 1,
    values: {"p":2,"e":1},
    weight: 2
}
```

Nome **name** è il nome da mostrare subito, **real_name** viene invece mostrato se l'oggetto è già conosciuto o se è stato identificato.
Per type creo una nuova issue.
Ho creato 3 valori, poi vediamo, è comunque tutto molto teorico ;)

**Comment by sincontri** [comment]
La cartella delle icone è **item**

**Comment by sincontri** [comment]
Elimino i campi value1/2/3 e ne metto uno in formato JSON.
Temo poi che ogni object **type** avrà il suo formato JSON in values, ad esempio per ARMOUR:

``` javascript
{
  "p": 2 (valore di protezione armatura),
  "e": 1 (ingombro)
}
```

Saranno da definire meglio man mano che creiamo object types e li usiamo.

**Comment by NikolasMosca** [comment]
mmm.. vedo il dato..ma non riesco a parsarlo :-(

**Comment by sincontri** [comment]
Come mai? Errore?

**Comment by NikolasMosca** [comment]
Come spiegato a voce (ed è gia stato risolto) non era scritto bene il json.. che di conseguenza andava in errore

**Comment by sincontri** [comment]
A posto per adesso.
